{% set name = "aioguest" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aioguest-{{ version }}.tar.gz
  sha256: b0bad95272592703379ada3d69f442c73b2cb64075be21d8617049c75747904b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - attrs >=21.3.0
    - greenlet
    - trio >=0.16.0
    - sniffio >=1.3.0
    - outcome

test:
  imports:
    - aioguest
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/oremanj/aioguest
  summary: Run asyncio and another event loop in the same thread
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE
    - LICENSE.APACHE2
    - LICENSE.MIT

extra:
  recipe-maintainers:
    - dhirschfeld
